### ISSUE TITLE
Error on dashboard after update.

### ISSUE THREAD

**Issue by devcflynn** [themosis/framework#195]
When in debug mode I have this error after logging into the admin dashboard:
```
Unhandled Exception
Message:
Trying to get property of non-object
Location:
/home/chris/Projects/blackstone/tmhu/cms/htdocs/cms/wp-includes/capabilities.php on line 1193
Stack Trace:
#0 /home/chris/Projects/blackstone/tmhu/cms/htdocs/content/themes/toyota/functions.php(216): Themosis\Error\Error::native(8, 'Trying to get p...', '/home/chris/Pro...', 1193)
#1 /home/chris/Projects/blackstone/tmhu/cms/htdocs/cms/wp-includes/capabilities.php(1193): {closure}(8, 'Trying to get p...', '/home/chris/Pro...', 1193, Array)
#2 [internal function]: map_meta_cap('read_post', 1, '1')
#3 /home/chris/Projects/blackstone/tmhu/cms/htdocs/cms/wp-includes/capabilities.php(999): call_user_func_array('map_meta_cap', Array)
#4 [internal function]: WP_User->has_cap('read_post', '1')
#5 /home/chris/Projects/blackstone/tmhu/cms/htdocs/cms/wp-includes/capabilities.php(1395): call_user_func_array(Array, Array)
#6 /home/chris/Projects/blackstone/tmhu/cms/htdocs/cms/wp-admin/includes/dashboard.php(774): current_user_can('read_post', '1')
#7 /home/chris/Projects/blackstone/tmhu/cms/htdocs/cms/wp-admin/includes/dashboard.php(659): wp_dashboard_recent_comments()
#8 [internal function]: wp_dashboard_site_activity('', Array)
#9 /home/chris/Projects/blackstone/tmhu/cms/htdocs/cms/wp-admin/includes/template.php(1074): call_user_func('wp_dashboard_si...', '', Array)
#10 /home/chris/Projects/blackstone/tmhu/cms/htdocs/cms/wp-admin/includes/dashboard.php(182): do_meta_boxes('dashboard', 'normal', '')
#11 /home/chris/Projects/blackstone/tmhu/cms/htdocs/cms/wp-admin/index.php(126): wp_dashboard()
#12 {main}
```

Being trying to figure this one out but it is in the CMS core code, which I prefer not to have to edit. Any thoughts?

Thanks!

**Comment by jlambe** [comment]
Hi,

I haven't yet received this error.
1. Which version of WordPress are you using?
2. Do you have any other plugins activated?

The error might be in core or not. You see, the error is triggered from the `capabilities.php` file but it apparently has been injected with a non-object value.
