### ISSUE TITLE
themosis via valet 

### ISSUE THREAD

**Issue by almokhtarbr** [themosis/framework#529]
First, let me say thanks to everyone involved in build Themosis, it's an excellent foundation for building modern systems atop of WP.

i installed themosis and i run it via valet and this error face me : 

```
Fatal error: Uncaught Error: Class ' ThemosisValetDriver.php ' not found in /Users/mbr/.composer/vendor/laravel/valet/cli/drivers/ValetDriver.php:77 Stack trace: #0 /Users/mbr/.composer/vendor/laravel/valet/server.php(107): ValetDriver::assign('/Volumes/HHD/de...', 't2', '/') #1 {main} thrown in /Users/mbr/.composer/vendor/laravel/valet/cli/drivers/ValetDriver.php on line 77
```

i had make like @ramon-villain  say in https://github.com/themosis/framework/issues/416#issuecomment-299458314
 thank you

**Comment by KevinBatdorf** [comment]
@almokhtarbr I replied to the other thread. Can you describe how you set up Valet and how you use it?

Can you type `valet on-latest-version` and what do you see?

**Comment by almokhtarbr** [comment]
@KevinBatdorf i had set up valet like docs in laravel says and when i type ```valet on-latest-version```
it give me ```YES``` ,

**Comment by KevinBatdorf** [comment]
@almokhtarbr Can you post your ThemosisValetDriver.php?

**Comment by almokhtarbr** [comment]
yeah, 
```
<?php

class ThemosisValetDriver extends BasicValetDriver
{
    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return bool
     */
    public function serves($sitePath, $siteName, $uri)
    {
        return file_exists($sitePath . '/library/Thms/Config/Environment.php');
    }

    /**
     * Determine if the incoming request is for a static file.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string|false
     */
    public function isStaticFile($sitePath, $siteName, $uri)
    {
        if (file_exists($staticFilePath = $sitePath . '/htdocs' . $uri)) {
            return $staticFilePath;
        } elseif ($this->isActualFile($staticFilePath = $sitePath . $uri)) {
            return $staticFilePath;
        }

        return false;
    }

    /**
     * Get the fully resolved path to the application's front controller.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string
     */
    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        if (strpos($uri, '/cms/') !== false) {
            $dynamicCandidates = [
                $this->asActualFile($sitePath, $uri),
                $this->asPhpIndexFileInDirectory($sitePath, $uri),
                $this->asHtmlIndexFileInDirectory($sitePath, $uri),
            ];
            foreach ($dynamicCandidates as $id => $candidate) {
                if ($this->isActualFile($candidate)) {
                    $_SERVER['PHP_SELF'] = $uri;
                    $_SERVER['SCRIPT_FILENAME'] = $candidate;
                    $_SERVER['SCRIPT_NAME'] = str_replace($sitePath, '', $candidate);
                    $_SERVER['DOCUMENT_ROOT'] = $sitePath;

                    return $candidate;
                }
            }
        }

        return $sitePath . '/htdocs/index.php';
    }

    /**
     * Redirect to uri with trailing slash.
     *
     * @param  string $uri
     * @return string
     */
    private function forceTrailingSlash($uri)
    {
        if (substr($uri, -1 * strlen('/wp-admin')) == '/wp-admin') {
            header('Location: ' . $uri . '/');
            die;
        }

        return $uri;
    }

    /**
     * Mutate the incoming URI.
     *
     * @param  string  $uri
     * @return string
     */
    public function mutateUri($uri)
    {
        return rtrim('/htdocs' . $uri, '/');
    }
}```

**Comment by KevinBatdorf** [comment]
Mine is here if you want to try it instead:  https://gist.github.com/KevinBatdorf/67942f88ff4b5238b8dde4222472a2f4

What does `valet which` and `valet links` say?

**Comment by almokhtarbr** [comment]
valet links : 
☁  ~  valet links
```
+-------------+-----+-------------------------+--------------------------------------+
| Site        | SSL | URL                     | Path                                 |
+-------------+-----+-------------------------+--------------------------------------+
| t2          |  X  | https://t2.dev          | /Volumes/HHD/dev/themosis/t2         |
| udemy_clone |  X  | https://udemy_clone.dev | /Volumes/HHD/dev/laravel/udemy_clone |
```
and valet which give me a long error : 
```
☁  ~  valet which
Password:
PHP Fatal error:  Uncaught Error: Class ' ThemosisValetDriver.php ' not found in /Users/mbr/.composer/vendor/laravel/valet/cli/drivers/ValetDriver.php:77
Stack trace:
#0 /Users/mbr/.composer/vendor/laravel/valet/cli/valet.php(160): ValetDriver::assign('/Users/mbr', 'mbr', '/')
#1 [internal function]: Silly\Application->{closure}()
#2 /Users/mbr/.composer/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array)
#3 /Users/mbr/.composer/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call(Object(Closure), Array)
#4 /Users/mbr/.composer/vendor/symfony/console/Command/Command.php(249): Silly\Application->Silly\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/mbr/.composer/vendor/symfony/console/Application.php(886): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/mbr/.composer/vendor/symfony/cons in /Users/mbr/.composer/vendor/laravel/valet/cli/drivers/ValetDriver.php on line 77

Fatal error: Uncaught Error: Class ' ThemosisValetDriver.php ' not found in /Users/mbr/.composer/vendor/laravel/valet/cli/drivers/ValetDriver.php:77
Stack trace:
#0 /Users/mbr/.composer/vendor/laravel/valet/cli/valet.php(160): ValetDriver::assign('/Users/mbr', 'mbr', '/')
#1 [internal function]: Silly\Application->{closure}()
#2 /Users/mbr/.composer/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(Closure), Array)
#3 /Users/mbr/.composer/vendor/mnapoli/silly/src/Application.php(95): Invoker\Invoker->call(Object(Closure), Array)
#4 /Users/mbr/.composer/vendor/symfony/console/Command/Command.php(249): Silly\Application->Silly\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /Users/mbr/.composer/vendor/symfony/console/Application.php(886): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /Users/mbr/.composer/vendor/symfony/cons in /Users/mbr/.composer/vendor/laravel/valet/cli/drivers/ValetDriver.php on line 77
```

**Comment by KevinBatdorf** [comment]
Where did you put the ThemosisValetDriver.php file?

**Comment by almokhtarbr** [comment]
./valet/Drivers/ ThemosisValetDriver.php

**Comment by almokhtarbr** [comment]
is that the path ?

**Comment by KevinBatdorf** [comment]
Seems right to me. You might want to reinstall Valet and see, otherwise post the error from `valet which` on the valet github or maybe laracasts.com forums.

Did you try using my file? I dont think it will make a difference, but might as well try

**Comment by almokhtarbr** [comment]
yes i did it but nothing change . i will reinstall Valet and i will see.
Thanks a lot

**Comment by KevinBatdorf** [comment]
Check `valet paths` looks correct too.

**Comment by almokhtarbr** [comment]
yes , 
```
[
    "/Users/mbr/.valet/Sites"
]
```

**Comment by almokhtarbr** [comment]
it give me that : /Users/mbr/.valet/Drivers/SampleValetDriver.php

**Comment by KevinBatdorf** [comment]
@almokhtarbr Try without `die();` or put the die statement outside the loop. You should see the themosis driver there, and you should be able to confirm whether the class loads.

**Comment by almokhtarbr** [comment]
that what it give me now  ?: ```/Users/mbr/.valet/Drivers/ ThemosisValetDriver.php /Users/mbr/.valet/Drivers/SampleValetDriver.php```

**Comment by KevinBatdorf** [comment]
Can you show me the code?

**Comment by KevinBatdorf** [comment]
You can try to confirm that file is being loaded by printing out it's contents, maybe something like this:

echo file_get_contents($path.'/'.$file);

Also, you can try to call the class too, `new ThemosisValetDriver();` since this is the code that is breaking for you. 

My guess is the file is empty though, which is why the class doesn't load.
