### ISSUE TITLE
JS bug with Wordpress 5.9

### ISSUE THREAD

**Issue by ligne13** [themosis/framework#837]
- Themosis Version: 2.1.0
- WordPress Version: 5.9
- PHP Version: 7.4

### Description

After upgrading to Wordpress 5.9, There a JS bug in the console when trying to edit a post/page within the Block Editor. Nothing is displayed, just a white screen.
The JS error in the console is :

```
TypeError: l.styles.forEach is not a function
    at edit-post.min.js:7:93641
    at Object.useMemo (react-dom.min.js:220:462)
    at c.useMemo (react.min.js:30:236)
    at zt (edit-post.min.js:7:93610)
    at Le (react-dom.min.js:100:3)
    at Pj (react-dom.min.js:231:183)
    at di (react-dom.min.js:168:305)
    at Nj (react-dom.min.js:168:236)
    at sc (react-dom.min.js:168:96)
    at gf (react-dom.min.js:162:109)
Ye @ react-dom.min.js?ver=17.0.1:141
```

I tried by disabling all plugins and with the twentytwentyone theme.

**Comment by jlambe** [comment]
This is not related to the framework scripts. You can verify by disabling them from `Hooks/Application.php` file for example. It seems there is an error in the WordPress core script file `edit-post.min.js` file.
